name: Deploy

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jungsoft/deployer-cli
    steps:
      - name: Run Commands
        run: |
          deployer up --file docker-compose.github.yml
