name: Deploy

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  test-docker:
    name: Docker Tests
    runs-on: ubuntu-latest

    container:
      image: jungsoft/deployer-cli

    # Run a local registry to push to
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v5

      - name: Run the Container
        id: run
        env:
          INPUT_WHO_TO_GREET: Mona Lisa Octocat
        run: |
          docker run \
            --env INPUT_WHO_TO_GREET="${{ env.INPUT_WHO_TO_GREET }}"

      - name: Run Deployer Commands
        id: deployer
        run: |
          deployer up --file docker-compose.github.yml
